platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: concourse-hello-world

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd concourse-hello-world
    chmod +x gradlew
    ./gradlew -P version=$(cat ../version/number) build
    pwd
    cp build/libs/concourse-hello-world*.jar ../../build-output
